# Generated by Django 4.0.1 on 2022-01-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CkDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, db_collation='Cyrillic_General_CI_AS', null=True)),
                ('link', models.CharField(db_collation='Latin1_General_100_CI_AS', max_length=255)),
                ('level_id', models.IntegerField()),
                ('division_id', models.IntegerField()),
                ('theme_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ck_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CkDocumentsDivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=124, null=True)),
            ],
            options={
                'db_table': 'ck_documents_divisions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CkDocumentsLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, db_collation='Cyrillic_General_CI_AS', max_length=45, null=True)),
            ],
            options={
                'db_table': 'ck_documents_levels',
                'managed': False,
            },
        ),
    ]
